### ISSUE TITLE
Error for 'validation_file_names.p'

### ISSUE THREAD

**Issue by XinhaoMei** [haantran96/wavetransformer#1]
Hi, I want to retrain the model. 
But I have the error: "No such file or directory: 'data/WT_pickles/validation_file_names.p'"
There is no validation_file_names.p in WT_pickles.
Could you tell me how to solve this? Thanks a lot!

**Comment by ghost** [comment]
Hi XinhaoMei, I have updated the file validation_file_names.p under WT_pickles https://github.com/haantran96/wavetransformer/tree/main/data/WT_pickles , please help pull the file.

**Comment by XinhaoMei** [comment]
> Hi XinhaoMei, I have updated the file validation_file_names.p under WT_pickles https://github.com/haantran96/wavetransformer/tree/main/data/WT_pickles , please help pull the file.
Hi, thanks a lot.
I followed the instruction to create the dataset. However, there is no validation directory in data_splits, this might be the problem. I don't know whether I was wrong during dataset creation.

**Comment by ghost** [comment]
Hi, the validation split is just a subset of the development split. You can simply create a symbolic link like this:
`ln -s link_to_development_split validation`.

**Comment by XinhaoMei** [comment]
Thank you very much!
I can run it successfully now!
